version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    #build: ./DjangoAPI/atbapi
    image: mrsamix/python_django_api:latest
    container_name: django
    env_file:
      - .env
    volumes:
      - image_data:/app/images
    ports:
      - "8361:8000"
    depends_on:
      - db

  front:
    #build: 
    #  context: ./react-ts
    #  args:
    #    VITE_API_URL: ${VITE_API_URL}
    image: mrsamix/python_django_react
    container_name: front
    depends_on:
      - server
    ports:
      - "3571:80"

volumes:
  postgres_data:
  image_data: